### ISSUE TITLE
Unable to change `UITextField` floating label colour

### ISSUE THREAD

**Issue by idikic** [Judopay/JudoKit#120]
Hello,

I'm using the latest version of Your **JudoKIT Swift SDK**. I'm using **Theme** to customise UI.
However I'm unable to change the colour of **UITextField** _floating label_. 

I have attached and example of this, in my case the _floating label_ would be **CVV** when the field is **active**.

![screen shot 2016-07-04 at 18 58 39](https://cloud.githubusercontent.com/assets/2021137/16576744/760a3610-4291-11e6-9d15-f8f3e7d96270.png)

Thanks for any help, and I have to say, **Theme** is excellent addition for easy modification!

Have a nice day

**Comment by ashleybarrett** [comment]
Morning,

Thank you or raising this. Changing the colour of the floating label isn't in in our current build. I'll speak to our product owner and see if I can get this work added in.

Thanks,

Ashley

**Comment by idikic** [comment]
Thanks @ashleybarrett!
