### ISSUE TITLE
Unable to change `LoadingBlockView` text colour and spinner colour

### ISSUE THREAD

**Issue by idikic** [Judopay/JudoKit#122]
Hello,

I'm having issues with `judoLoadingBlockViewColor`, if block is of colour `UIColor.whiteColor()`,  text will not be visible.

Also I'm unable to change spinner colour which can also be an issue with certain colours.

Thanks for your help.

Have a nice day.

**Comment by ashleybarrett** [comment]
Morning,

Thank you for raising this, let me take a look and get back to you.

Just for our records, which company are you integrating with please?

Thanks,

Ashley

**Comment by idikic** [comment]
Good morning Ashley,

I’m currently integrating for the TradeCore.

Have a nice day

Ivan Dikic

— Sent from
https://polymail.io/

On Mon, 11 Jul 2016 at 11:49 Ashley Barrett

<
mailto:Ashley Barrett <notifications@github.com>
> wrote:

Morning,

Thank you for raising this, let me take a look and get back to you.

Just for our records, which company are you integrating with please?

Thanks,

Ashley

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/JudoPay/JudoKit/issues/122#issuecomment-231689945
, or
https://github.com/notifications/unsubscribe/AB7XERbqvA-6Y83ISV-Zss9JuvPg2QSAks5qUhGygaJpZM4JJGaK
.

https://github.com/JudoPay/JudoKit/issues/122#issuecomment-231689945
