### ISSUE TITLE
Unable to integrate JudoKit in Framework

### ISSUE THREAD

**Issue by sureshr207** [Judopay/JudoKit#165]
I am using JudoKit & it is really useful.

We have installed this via CocoaPods in our framework Xcode project for iOS.
**Context**:
Platform : iOS
Project type: Framework
Language : swift
How Judokit installed: via cocoapods

Problem:

Reusing a workflow that involves Judokit integration across multiple apps. Hence created a framework to abstract this workflow. Except for the Judokit part, everything works alright.

Despite our efforts we get `dyld: Library not loaded: @rpath/DeviceDNA.framework/DeviceDNA`
Please let us know what needs to be done so that we use this.

**Comment by zfoltin** [comment]
Hi @sureshr207,

DeviceDNA is a required dependency of JudoKit. Does adding it to your framework help?
