### ISSUE TITLE
Pay Button action failed

### ISSUE THREAD

**Issue by smilydronavalli** [Judopay/JudoKit#181]
Hi,

When I click on paybutton,I got the folllwoing error please kindly suggest me

Error Domain=com.judo.error Code=3 "Sorry, we're currently unable to process this request." UserInfo={JPErrorTitleKey=Unable to process, NSLocalizedDescription=Sorry, we're currently unable to process this request., NSLocalizedFailureReason=The payment method (card details, token or PKPayment) has not been set for a transaction that requires it (custom UI)}
Thanks
Smily

**Comment by mikehancock** [comment]
The error message is explaining that you are missing some of the payment details that are required to process a payment, I assume you are using a custom UI, are you able to verify that you are setting the card / token / ApplePay details?
