### ISSUE TITLE
Carthage instructions don't work now you've moved to TrustKit

### ISSUE THREAD

**Issue by termorrell** [Judopay/JudoKit#186]
When following the Carthage instructions in the repo, the project fails to compile as TrustKit is missing. I believe you need to add TrustKit to the Cartfile so it is built separately?

**Comment by sam2000** [comment]
Yes it is broken as far as Carthage users are concerned. Please can you fix this?

**Comment by zfoltin** [comment]
Thanks for reporting the issue @termorrell and @sam2000 
With version https://github.com/Judopay/JudoKit/releases/tag/7.1.1 it should be fixed now. I've also updated the [wiki](https://github.com/JudoPay/JudoKit/wiki/Carthage) 🚀
