### ISSUE TITLE
Swift 4.2 and Xcode 10 support

### ISSUE THREAD

**Issue by snamrata007** [Judopay/JudoKit#189]
Can you please update this library for swift 4.2 and Xcode 10?

**Comment by zfoltin** [comment]
Hey @snamrata007, thanks for raising this issue. The update is on our roadmap, coming up in a week if all goes well 👍

**Comment by zfoltin** [comment]
Released version 8.0.0 https://github.com/Judopay/JudoKit/releases/tag/8.0.0
https://cocoapods.org/pods/JudoKit
