### ISSUE TITLE
Use of deprecated UIWebView

### ISSUE THREAD

**Issue by OJDee** [Judopay/JudoKit#194]
Apple has begun to send warnings on every submission to AppStoreConnect warning of use of a deprecated class, UIWebView

3DSWebView inherits UIWebView
JudoPayViewController conforms to UIWebViewDelegate

The use of WKWebView is assumed as a direct replacement for WKWebView. Is this update planned for JudoKit?

**Comment by freddy-onco** [comment]
@OJDee thank you , we are aware of this necessary change , and we will carry out an upgrade of the SDK

**Comment by freddy-onco** [comment]
@OJDee just a quick note to let you know Swift will be updated within the next few days.

**Comment by web30india** [comment]
Hey, can you please update us when this issue will be fixed?

**Comment by wilson-sit-judo** [comment]
@web30india  Please take a look on our ObjectiveC SDK https://github.com/Judopay/JudoKitObjC

**Comment by ruipfcosta** [comment]
Hi @wilson-sit-judo, are there any updates on this? Apple has recently communicated the deadlines in regards to UIWebView deprecation:

> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

Source: https://developer.apple.com/news/?id=12232019b

**Comment by wilson-sit-judo** [comment]
Hi @ruipfcosta - I'm afraid we're no longer going to be updating the Swift SDK and we're advising users to migrate over to our Objective-C SDK.  Please refer to https://github.com/JudoPay/JudoKitObjC where you'll find a Swift Example app to refer to.

**Comment by adamwaite** [comment]
You're not supporting the Swift SDK, and advising we use the Objective-C SDK? Really?

**Comment by wilson-sit-judo** [comment]
Hi @adamwaite 
We've streamlined our SDKs for iOS which we still supports Swift integration methods as a wrapper around ObjC.
Please refer to the following for the Swift Example app https://github.com/Judopay/JudoKit-iOS/tree/master/Examples/SwiftExampleApp
