### ISSUE TITLE
Class JudoShield, SSKeychainQuery and SSKeychain is implemented in both ...

### ISSUE THREAD

**Issue by idikic** [JudoPay/JudoKit#68]
Hello, after upgrading to version 5.5.1 of JudoKIT (Swift) I get the following warnings:

`objc[70838]: Class JudoShield is implemented in both ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoKit.framework/JudoKit and ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoShield.framework/JudoShield. One of the two will be used. Which one is undefined.
objc[70838]: Class SSKeychainQuery is implemented in both ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoKit.framework/JudoKit and ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoShield.framework/JudoShield. One of the two will be used. Which one is undefined.
objc[70838]: Class SSKeychain is implemented in both ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoKit.framework/JudoKit and ../Library/Developer/CoreSimulator/Devices/6F4B03BB-1A43-48F8-96F1-3290496911F6/data/Containers/Bundle/Application/21467425-1AB7-437C-90F7-F5373647E40E/Test.app/Frameworks/JudoShield.framework/JudoShield. One of the two will be used. Which one is undefined.`

Not sure if this will cause any unwanted side effects :)?

Thanks for any help!

**Comment by Ryce** [comment]
Hi,

I am actually just on this issue. I hope to have a solution out today! Stay tuned

br
Ben

**Comment by Ryce** [comment]
which method of implementation did you use? Manual, Cocoapods or Carthage?

**Comment by idikic** [comment]
Hey Ben, ah sorry for not specifying this! I'm currently using Carthage.

**Comment by Ryce** [comment]
#70 we experienced some issues with JudoShield in general, this issue has been fixed and will be officially released after QA tomorrow (03/02/2016)
