### ISSUE TITLE
wrong info in README.md

### ISSUE THREAD

**Issue by andproff** [JudoPay/JudoKit#84]
hello you wrote in README.md
`pod 'JudoKit', '~> 6.1'`

but cocoapods return this error:
```
[!] Unable to satisfy the following requirements:
- `JudoKit (~> 6.1)` required by `Podfile`
```
so now last version in cocoapods is 6.0.0

**Comment by Ryce** [comment]
Hi,

the version on master is currently not released. If you look at [our tags](https://github.com/JudoPay/JudoKit/releases) You will see the released versions.

the master will always be our wip branch.
