### ISSUE TITLE
missing required architecture arm64

### ISSUE THREAD

**Issue by andproff** [JudoPay/JudoKit#85]
Hello I tried made build for iPhone with connected JudoKit framework through cocoapods without use any methods (just empty single view project) of course I opened .workspace
but compiler returned error:
```
ld: warning: directory not found for option '-F/Users/proff/Desktop/TestJudo/Pods/JudoShield/Source'
ld: warning: ignoring file /Users/proff/Desktop/TestJudo/Pods/JudoShield/Framework/JudoShield.framework/JudoShield, missing required architecture arm64 in file /Users/proff/Desktop/TestJudo/Pods/JudoShield/Framework/JudoShield.framework/JudoShield (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JudoShield", referenced from:
      type metadata accessor for __ObjC.JudoShield in JudoPayViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Ryce** [comment]
Hi @andproff,

thanks for discovering this. I think we have found the issue. Just for testing purposes, can you execute on a simulator?

**Comment by andproff** [comment]
Hi Ben on simulator all is ok

**Comment by Ryce** [comment]
Hi @andproff,

we just released a new JudoShield version, please do a `pod update` and everything should work fine!

br
Ben
